import type { Metadata } from "next";
import "../globals.css"

export const metadata: Metadata = {
  title: "Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
             {children}
      </body>
    </html>
  );
}
