import { getPages } from "@/sanity/sanity-utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Me",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto py-10 px-10">
        <header className="flex items-center justify-between">
          <Link
            href={"/"}
            className="bg-clip-text text-transparent bg-gradient-to-r from-orange-400 via-red-500 to-purple-600"
          >
            Nottidge
          </Link>

          <div className="flex items-center gap-4 text-sm text-gray-600">
            <Link href={`/articles`} className="hover:underline">
              Articles
            </Link>
            {pages.map((page) => (
              <Link
                href={`/${page.slug}`}
                key={page._id}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
