import { getPages } from "@/sanity/sanity-utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "../globals.css";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Me",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto py-10 px-10">
        <Header pages={pages} />

        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
